jobs:
  include:
    - stage: trigger downstream
      script: |
          curl -LO --retry 3 https://raw.githubusercontent.com/plume-lib/trigger-travis/master/trigger-travis.sh
          sh trigger-travis.sh --branch develop devgaram devgaram.github.io $TRAVIS_ACCESS_TOKEN
